# docker-compose of all services needed to fully test the quicknote plugins
# rabbitmq:3.11-management - RabbitMQ server with management console

version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
